apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-deployment
  labels:
    app: ttt
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: ttt
  
  template:
    metadata:
      labels:
        app: ttt
    spec:
      containers:
      - name: ttt
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
